   
name: build-deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Build
      run: go build -v cmd/zracni-udar-service/main.go

    - name: Set SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        context: .
        file: ./Dockerfile
        push: true 
        tags: horvatic/zracni-udar-service:${{ steps.vars.outputs.sha_short }}
    
    - name: Save SHA
      env: 
        TAG: ${{ steps.vars.outputs.sha_short }}
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
        MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
        FRONT_END_HOST: ${{ secrets.FRONT_END_HOST }}
      run: |
         envsubst < deploy/base/deployment.yaml > tempbase
         cat tempbase > deploy/base/deployment.yaml
         envsubst < deploy/dev/secret.yaml > tempsecret
         cat tempsecret > deploy/dev/secret.yaml
         rm tempbase tempsecret
  
    - name: 'Upload Deploy'
      uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: deploy
        retention-days: 5
        
  dev:
    name: Deploy To Dev
    environment:
      name: dev
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v1
  
    - name: Setup kubectl
      env: 
        K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
      run: |
        mkdir -p $HOME/.kube
        echo "${K8S_CONFIG}" | base64 --decode > $HOME/.kube/config
      
    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: deploy
      
    - name: Apply pods
      run: kubectl apply -k dev -n dev
      
    - name: Wait For Deployment To Start
      run: sleep 10s
      
    - name: Wait For Pods To Start
      run: kubectl wait --for=condition=ready pod -l app=gokub-tester -n dev --timeout=10m
